src/Entity/Avis.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AvisRepository")
 */
class Avis
{
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="integer")
     */
    private $Note;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Commentaire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\Pro", inversedBy="AvisObtenu")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Id_Pro;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\Particulier", inversedBy="AvisLaisse")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Id_Particulier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->Note;
    }

    public function setNote(int $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->Commentaire;
    }

    public function setCommentaire(string $Commentaire): self
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getIdPro(): ?Pro
    {
        return $this->Id_Pro;
    }

    public function setIdPro(?Pro $Id_Pro): self
    {
        $this->Id_Pro = $Id_Pro;

        return $this;
    }

    public function getIdParticulier(): ?Particulier
    {
        return $this->Id_Particulier;
    }

    public function setIdParticulier(?Particulier $Id_Particulier): self
    {
        $this->Id_Particulier = $Id_Particulier;

        return $this;
    }
}

src/Entity/Particulier.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParticulierRepository")
 */
class Particulier implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="2")
     * @Assert\NotBlank
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Adresse;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Length(max="5")
     * @Assert\NotBlank
     */
    private $CP;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     * @Assert\NotBlank
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="6", max="32")
     */
    private $MotDePasse;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Ville;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Avis", mappedBy="Id_Particulier")
     * @ORM\OrderBy({"Date" = "DESC"})
     */
    private $AvisLaisse;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\IsTrue(message="Veuillez cocher la case")
     */
    private $CGU;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $newsletter;

    public function __construct()
    {
        $this->isActive = true;
        $this->roles = ['ROLE_USER'];
        $this->AvisLaisse = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getCP(): ?int
    {
        return $this->CP;
    }

    public function setCP(int $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->MotDePasse;
    }

    public function setMotDePasse(string $MotDePasse): self
    {
        $this->MotDePasse = $MotDePasse;

        return $this;
    }


    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_PARTICULIER'];
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword()
    {
        return $this->getMotDePasse();
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->Email,
            $this->MotDePasse,
        ]);
    }

    public function getUsername()
    {
        return $this->getEmail();
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->Email,
            $this->MotDePasse
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvisLaisse(): Collection
    {
        return $this->AvisLaisse;
    }

    public function addAvisLaisse(Avis $avisLaisse): self
    {
        if (!$this->AvisLaisse->contains($avisLaisse)) {
            $this->AvisLaisse[] = $avisLaisse;
            $avisLaisse->setIdParticulier($this);
        }

        return $this;
    }

    public function removeAvisLaisse(Avis $avisLaisse): self
    {
        if ($this->AvisLaisse->contains($avisLaisse)) {
            $this->AvisLaisse->removeElement($avisLaisse);
            // set the owning side to null (unless already changed)
            if ($avisLaisse->getIdParticulier() === $this) {
                $avisLaisse->setIdParticulier(null);
            }
        }

        return $this;
    }

    public function getCGU(): ?bool
    {
        return $this->CGU;
    }

    public function setCGU(bool $CGU): self
    {
        $this->CGU = $CGU;

        return $this;
    }

    public function getNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(?bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }
}

src/Controller/ParticulierController.php
<?php


namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class ParticulierController extends AbstractController
{
    /**
     * @Route("/particulier", name="particulier")
     * @return Response
     */
    public function index()
    {
        return $this->render('particuliers/particuliers.html.twig');
    }
}

templates/particuliers/account_infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}👋AccountController!{% endblock %}


{% block body %}
<div class="container">
    <div class="row">
    <h2>Mes infos</h2>
   <div class="container-fluid">
        <div class="row">
            <div class="col-12 bg-dark" id="form">
                <div class="container my-5" id="form2">
                    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                    {{ form_widget(form) }}

                    <button class="btn btn-success">Modifier</button>
                    {{ form_end(form) }}
                </div>
            </div>

            <div class="col-12">
                <h2>Derniers avis laissés</h2>
                {% for avis in app.user.AvisLaisse %}
                    <div class="avis">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                        <meta itemprop="datePublished" content="{{ avis.Date|date('Y-m-d') }}">{{ avis.Date|date('d F Y') }}
                        <span>
                            {% for i in 1..avis.note %}
                                &#x2B50;
                            {% endfor %}
                            {% for i in (avis.note+1)..5 %}
                                &#x2606;
                            {% endfor %}
                            pour {{ avis.IdPro.Entreprise }}
                        </span>
                        <p class="blockquote">
                        <p class="mb-0">{{ avis.Commentaire }}</p>
                        </p>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/particuliers/particuliers.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="banner1">
        <img src="/images/banner_particulier.jpg" class="img-fluid" alt="Bannière page particuliers">
    </div>
        <h2 class="info1">Vous êtes un particulier...</h2>
    <div class="container">
        <section class="pres_part">
            <div class=""container">
                <div class="row">
                    <div class="col-4">
                        <div class="icon1 my-4 mx-auto"><img src="/images/icone_concretisation.svg"></div>
                        <h4 class="text-center" style="color: #ff5858">Concrétisez vos projets</h3>
                        <div class="bloc-content">
                            <p class="text-center">Vous cherchez un artisan pour réaliser des travaux d'aménagement ou de rénovation de votre habitation...</p>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="icon1 my-4 mx-auto"><img src="/images/icone_specialiste.svg"></div>
                        <h4 class="text-center" style="color: #ff5858">Trouvez un spécialiste</h3>
                        <div class="bloc-content">
                            <p class="text-center">Vous cherchez un artisan spécialisé à qui vous pourriez confier la réalisation des travaux...</p>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="icon1 my-4 mx-auto"><img src="/images/icone_evaluation.svg"></div>
                        <h4 class="text-center" style="color: #ff5858">Évaluez votre collaborateur</h3>
                        <div class="bloc-content">
                            <p class="text-center">Vous désirez partager votre expérience afin d'aider d'autres personnes désirant réaliser des travaux... </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- Module Call To Action -> Connexion -->
    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
    {% else %}
        <br>
        <div id="banner1" style="border-bottom: 2px solid #ff5858">
        {{ include('CallToAction/cta-connexion.html.twig') }}
        </div>
        <br>
    {% endif %}
    <!-- Module Call To Action -> BackToTop -->
    <br>
    {{ include('CallToAction/cta-backtotop.html.twig') }}

{% endblock %}