src/Entity/Pro.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProRepository")
 * @ORM\Entity
 * @UniqueEntity(fields={"Email"}, message="cet email est déjà connu !")
 * @UniqueEntity(fields={"Entreprise"}, message="cette entreprise est déjà connu !")
 */
class Pro implements UserInterface, Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="2")
     */
    private $Entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="2")
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="2")
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $NumeroSiret;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Adresse;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Length(min="5", max="5")
     */
    private $CP;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern     = " /^(?:(?:\+|00)33[\s.\-\/]{0,3}(?:\(0\)[\s.\-\/]{0,3})?|0)[1-9](?:(?:[\s.\-\/]?\d{2}){4}|\d{2}(?:[\s.\-\/]?\d{3}){2})$/")
     */
    private $Telephone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     * @Assert\NotBlank
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $SiteWeb;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $SecteurActivite;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="6", max="32")
     */
    private $MotDePasse;

    /**
     * @ORM\Column(nullable=true)
     *@Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"application/pdf", "image/png", "image/jpeg", "image/svg", "image/jpg"},
     *     mimeTypesMessage = "Veuillez télécharger un fichier au format jpeg/png/pdf "
     * )
     */
    private $Logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PageFacebook;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\IsTrue(message="Veuillez cocher la case")
     */
    private $CGU;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Newsletter;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $Ville;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Avis", mappedBy="Id_Pro")
     * @ORM\OrderBy({"Date" = "DESC"})
     */
    private $AvisObtenu;

    public function __construct()
    {
        $this->Id_contact_pro = new ArrayCollection();
        $this->AvisObtenu = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEntreprise(): ?string
    {
        return $this->Entreprise;
    }

    public function setEntreprise(string $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNumeroSiret(): ?string
    {
        return $this->NumeroSiret;
    }

    public function setNumeroSiret(string $NumeroSiret): self
    {
        $this->NumeroSiret = $NumeroSiret;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getCP(): ?int
    {
        return $this->CP;
    }

    public function setCP(int $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->SiteWeb;
    }

    public function setSiteWeb(string $SiteWeb): self
    {
        $this->SiteWeb = $SiteWeb;

        return $this;
    }

    public function getSecteurActivite(): ?string
    {
        return $this->SecteurActivite;
    }

    public function setSecteurActivite(string $SecteurActivite): self
    {
        $this->SecteurActivite = $SecteurActivite;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->MotDePasse;
    }

    public function setMotDePasse(string $MotDePasse): self
    {
        $this->MotDePasse = $MotDePasse;

        return $this;
    }

    public function getLogo()
    {
        return $this->Logo;
    }

    public function setLogo(File $file)
    {
        $this->Logo = $file;

        return $this;
    }

    /**
     * @return Collection|ContactPro[]
     */
    public function getIdContactPro(): Collection
    {
        return $this->Id_contact_pro;
    }

    public function addIdContactPro(ContactPro $idContactPro): self
    {
        if (!$this->Id_contact_pro->contains($idContactPro)) {
            $this->Id_contact_pro[] = $idContactPro;
            $idContactPro->setIDPro($this);
        }

        return $this;
    }

    public function removeIdContactPro(ContactPro $idContactPro): self
    {
        if ($this->Id_contact_pro->contains($idContactPro)) {
            $this->Id_contact_pro->removeElement($idContactPro);
            // set the owning side to null (unless already changed)
            if ($idContactPro->getIDPro() === $this) {
                $idContactPro->setIDPro(null);
            }
        }

        return $this;
    }

    public function getPageFacebook(): ?string
    {
        return $this->PageFacebook;
    }

    public function setPageFacebook(string $PageFacebook): self
    {
        $this->PageFacebook = $PageFacebook;

        return $this;
    }

    public function getCGU(): ?bool
    {
        return $this->CGU;
    }

    public function setCGU(bool $CGU): self
    {
        $this->CGU = $CGU;

        return $this;
    }

    public function getNewsletter(): ?bool
    {
        return $this->Newsletter;
    }

    public function setNewsletter(bool $Newsletter): self
    {
        $this->Newsletter = $Newsletter;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvisObtenu(): Collection
    {
        return $this->AvisObtenu;
    }

    public function addAvisObtenu(Avis $avisObtenu): self
    {
        if (!$this->AvisObtenu->contains($avisObtenu)) {
            $this->AvisObtenu[] = $avisObtenu;
            $avisObtenu->setIDPro($this);
        }

        return $this;
    }

    public function removeAvisObtenu(Avis $avisObtenu): self
    {
        if ($this->AvisObtenu->contains($avisObtenu)) {
            $this->AvisObtenu->removeElement($avisObtenu);
            // set the owning side to null (unless already changed)
            if ($AvisObtenu->getIDPro() === $this) {
                $AvisObtenu->setIDPro(null);
            }
        }

        return $this;
    }

    public function averageNote(): int {
        $avisCount = count($this->AvisObtenu);
        if ($avisCount == 0) {
            return 0;
        }
        $total = 0;
        for ($i = 0; $i < $avisCount; $i++) {
            $total += $this->AvisObtenu[$i]->getNote();
        }
        return ($total + $avisCount / 2) / $avisCount;
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->Email,
            $this->MotDePasse,
        ]);
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->Email,
            $this->MotDePasse
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,

templates/_footer.html.twig
<!-- Footer -->
<footer class="text-light footer footer-expand-md footer-dark bg-dark" style="border-top: 2px solid #ff5858">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-lg-4 col-xl-3 my-3">
                <h5 class="apricot">À propos</h5>
                <hr class="mb-2 mt-0 d-inline-block mx-auto w-25" style="background-color: #ff5858">
                <p class="mb-0 text-light">
                    BricoTravoPro est un projet de fin d'études, réalisé dans le cadre de la formation Développeur/Intégrateur Web et applications mobiles, dispensé par WebForce3 Lille.
                </p>
            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto my-3">
                <h5 class="apricot">Informations</h5>
                <hr class="mb-2 mt-0 d-inline-block mx-auto w-25" style="background-color: #ff5858">
                <ul class="list-unstyled">
                    <li><a href="{{ path('qsn') }}">Qui sommes nous ?</a></li>
                    <li><a href="{{ path('contact-mail') }}">Contact</a></li>
                    <li><a href="{{ path('blog') }}">Blog</a></li>
                    <li><a href="{{ path('faq') }}">F.A.Q</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto my-3">
                <h5 class="apricot">Suivez-nous</h5>
                <hr class="mb-2 mt-0 d-inline-block mx-auto w-25" style="background-color: #ff5858">
                <ul class="list-unstyled">
                    <div class="row">
                        <li class="col-3"><a href="https://www.facebook.com/BricoTravoPro" target="_blank" alt="Lien vers Facebook"><i class="fab fa-facebook-f" aria-hidden="true" title="Facebook de BricoTravoPro"></i></a></li>
                        <li class="col-3"><a href="https://twitter.com/BricoTravoPro" target="_blank" alt="Liens vers Twitter"><i class="fab fa-twitter" aria-hidden="true" title="Twitter de BricoTravoPro"></i></a></li>
                    </div>
                </ul>
            </div>
            <div class="col-md-4 col-lg-3 col-xl-3 my-3">
                <h5 class="apricot">Contact</h5>
                <hr class="mb-2 mt-0 d-inline-block mx-auto w-25" style="background-color: #ff5858">
                <ul class="list-unstyled">
                    <li><i class="fa fa-home mr-2" style="color: #fbceb1" aria-hidden="true" title="Adresse postale de BricoTravoPro"></i> BricoTravoPro<br>
                        105 Avenue de la République<br>
                        59110 La Madeleine</li><br>
                    <li><i class="fa fa-envelope mr-2" style="color: #fbceb1" aria-hidden="true" title="Adresse de contact e-mail de BricoTravoPro"></i> contact@bricotravopro.com</li><br>
                    <li><i class="fa fa-phone mr-2" style="color: #fbceb1" aria-hidden="true" title="Coordonnées téléphoniques" de BricoTravoPro"></i> Téléphone<br>
                        <a href="tel:+33600000000">Appeler le 06 00 00 00 00</a><br>
                        <a href ="sms:+33600000000">Envoyer un SMS</a></li>
                </ul>
            </div>
            <br>
            <div class="container">
                <p class="text-light text-center m-0">Copyright &copy; BricoTravoPro {{ 'now' | date('Y') }} - <a href= "{{ path('CGU') }}" >Conditions Générales d'Utilisation</a> - <a href= "{{ path('mentions_legales') }}" >Mentions légales</a> </p>
            </div>
        </div>
    </div>
</footer>

templates/_navbar.html.twig
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="icon3 my-4 mx-auto" href="{{ path('home') }}">
            <img src="/images/logo_bricotravopro_general.svg" alt="logo BricoTravoPro" >
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            {% set route = app.request.attributes.get('_route') %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link {{ route == 'particulier' ? 'active' }}" href="{{ path('particulier') }}">Particuliers</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {{ route == 'professionnel' ? 'active' }}" href="{{ path('professionnel') }}">Professionnels</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <li class="nav-item">
                    <a class="nav-link text-dark mr-3" href="{{ path(is_granted('ROLE_PARTICULIER') ? 'user_infos' : 'pro_infos')}}">{{ app.user.nom }} {{ app.user.Prenom }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Déconnexion</a>
                {% else %}
                    <a class="nav-link {{ route == 'inscription_particulier' ? 'active' }}" href="{{ path('inscription_particulier') }}">Inscription particulier</a>
                    <a class="nav-link {{ route == 'inscription_professionnel' ? 'active' }}" href="{{ path('inscription_professionnel') }}">Inscription professionnel</a>
                    <a class="nav-link {{ route == 'login' ? 'active' }}" href="{{ path('login') }}">Connexion</a>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}BricoTravoPro{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
            <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
            <link rel="stylesheet" href="{{ asset('css/main.css') }}">
            <link rel="stylesheet" href="{{ asset('css/qsn.css') }}">
            <link rel="stylesheet" href="{{ asset('css/formulaireInscription.css') }}">
            <link rel="shortcut icon" href="/images/favicon_bricotravopro.ico" type="image/x-icon">
            <link rel="icon" href="/images/favicon_bricotravopro.png" type="image/png">
            <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
    {{ include('_navbar.html.twig') }}

    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="mt-4 alert alert-{{ label }} alert-dismissible fade show">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}

        {% block body %}{% endblock %}

    {{ include('_footer.html.twig') }}

        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% endblock %}
    </body>
</html>